import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faSun,
  faMoon,
  faPlus,
  faRightFromBracket,
  faRightToBracket,
  faUser,
  faComments,
  faChartPie,
  faChartBar,
  faChartArea,
  faFire,
  faClock,
  faPen,
  faPenToSquare,
  faChartColumn,
  faTrash,
  faPaperPlane,
  faCheck,
  faThumbsUp,
  faThumbsDown,
  faCircleQuestion,
  faCircleHalfStroke,
  faBars,
  faMagnifyingGlass,
  faFilter,
  faArrowDownWideShort,
  faUpRightFromSquare,
  faBold,
  faItalic,
  faUnderline,
  faStrikethrough,
  faListUl,
  faListOl,
  faQuoteRight,
  faHeading,
  faLink,
  faRotateLeft,
  faRotateRight,
  faScaleBalanced,
  faSeedling,
  faXmark,
  faFloppyDisk,
  faPaperclip,
  faStar,
  faStarHalfStroke,
  faBoxArchive,
  faLayerGroup,
  faCalendar,
  faIdCard,
} from '@fortawesome/free-solid-svg-icons'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

library.add(
  faSun,
  faMoon,
  faPlus,
  faRightFromBracket,
  faRightToBracket,
  faUser,
  faComments,
  faChartPie,
  faChartBar,
  faChartArea,
  faFire,
  faClock,
  faPen,
  faPenToSquare,
  faChartColumn,
  faTrash,
  faPaperPlane,
  faCheck,
  faThumbsUp,
  faThumbsDown,
  faCircleQuestion,
  faCircleHalfStroke,
  faBars,
  faMagnifyingGlass,
  faFilter,
  faArrowDownWideShort,
  faUpRightFromSquare,
  faBold,
  faItalic,
  faUnderline,
  faStrikethrough,
  faListUl,
  faListOl,
  faQuoteRight,
  faHeading,
  faLink,
  faRotateLeft,
  faRotateRight,
  faScaleBalanced,
  faSeedling,
  faXmark,
  faFloppyDisk,
  faPaperclip,
  faStar,
  faStarHalfStroke,
  faBoxArchive,
  faLayerGroup,
  faCalendar,
  faIdCard,
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
})
